server: 
  port: 8080
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/parcial_1?useSSL=false
    username: root
    password: Cris232322